#!/bin/bash
# Script for installing po-util for Travis CI
# bash <(curl -sL master.po-util.com/ci-install)

sudo apt install -y expect
curl -sLO https://raw.githubusercontent.com/nrobinson2000/po-util/master/po-util.sh
chmod +x po-util.sh
curl -sLO https://raw.githubusercontent.com/nrobinson2000/po-util/master/config-expect.sh
chmod +x config-expect.sh
./config-expect.sh
./po-util.sh install ~/github basic
