#!/bin/bash
# https://master.po-util.com/install

OS="$(uname -s)"

if [ "$OS" == "Linux" ];
then
  bash < ( curl -sL https://master.po-util.com/po-util.sh ) install
fi

if [ "$OS" == "Darwin" ];
then
  if hash brew 2>/dev/null;
  then
    echo "Homebrew is installed. Continuing..."
  else
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  brew tap nrobinson2000/po
  brew install po
  po install
fi
